/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 7.5 */
/* Thu Feb 17 08:28:20 2022 */

/* parameterized module instance */
dpr_2k_A64_B8 __ (.DataInA( ), .DataInB( ), .AddressA( ), .AddressB( ), 
    .ClockA( ), .ClockB( ), .ClockEnA( ), .ClockEnB( ), .WrA( ), .WrB( ), 
    .ResetA( ), .ResetB( ), .QA( ), .QB( ));
